services:
  tollservice.api:
    container_name: tollservice-api
    image: futondoker/tollserviceapi:v1
    build:
      context: .
      dockerfile: src/TollService.Api/Dockerfile

  db:
    image: postgis/postgis:16-3.4
    container_name: tolls-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tolls
    ports:
      - "5436:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
